### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by mikegee0101** [delighted/sketch-pull-to-center#1]
@mkdynamic Can you code review this when you have time. It's a bit verbose. Even if you're not familiar with some of the syntax, I think there are probably places where I've made the math overly complicated.

**Comment by mkdynamic** [comment]
- You probably want to add a license. Would suggest MIT license. Drop in a file called LICENSE, like this: https://github.com/mkdynamic/ke/blob/master/LICENSE.
- Another suggestion, add a section for contributing: https://github.com/mkdynamic/ke#contributing
- Would change the title in README to clarify "Sketch plugin – ..." or whatever
- The Demo part in the README would be nice. An animated inline GIF would be cool.
- Code looks good. It's plenty readable, I wouldn't suggest any changes.

**Comment by mkdynamic** [comment]
^^^ Above applies to both repos.

**Comment by mikegee0101** [comment]
No code changes? Even the parts where I do a bunch of conditionals to check
if things are past the artboard centers and where I'm deciding to add vs
subtract? Felt smelly.

**Comment by mikegee0101** [comment]
Also should I put myself as an author so people know a designer did it and
not our engineering team? :)

**Comment by mkdynamic** [comment]
Feel free to put yourself since you wrote it (personally, I would), but for not for that reason, lol.

Re: code, nope I wouldn't make any changes. It's a useful and general script for Sketch, it works and the code is easy to read. Job done, ship it. It **definitely** looks good enough to publish.
