### ISSUE TITLE
Pull to center for vertizes

### ISSUE THREAD

**Issue by toovy** [delighted/sketch-pull-to-center#2]
Hi delighted, 

thanks for the great plugin. I've searched for a similar functionality for quite a while. When selecting the vertices of a closed path it would be awesome to pull them to the center. Currently the solution does more or less only pull objects. Would it easily be possible to also pull vertices?

Thanks, BR, toovy

**Comment by mikegee0101** [comment]
@toovy Glad you like the plugin! As far as I know there isn't an easy way to adjust the points of a path. At least not that I have found :/
